### ISSUE TITLE
Unhandled exception when clicking empty autocomplete option in interpreter window

### ISSUE THREAD

**Issue by sad-dev** [mandiant/Ghidrathon#58]
I am using a fairly recent commit of ghidra (https://github.com/NationalSecurityAgency/ghidra/commit/9e8392187201128bad2b2b2daa1dc5eb37a9b4ca) and the latest (b7bedaf) of Ghidrathon

Autocomplete provides no completions for me:

![image](https://github.com/mandiant/Ghidrathon/assets/55233728/30e8872b-532e-4ca9-9966-af45a7d97f91)

and clicking it gives me an NPE (although this might be a Ghidra issue) :

```
Cannot invoke "java.util.List.get(int)" because "this.list" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because "this.list" is null
	at ghidra.app.plugin.core.interpreter.CodeCompletionListSelectionModel.setSelectionInterval(CodeCompletionWindow.java:378)
	at java.desktop/javax.swing.JList.setSelectionInterval(JList.java:2104)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.adjustSelection(BasicListUI.java:2931)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.mousePressed(BasicListUI.java:2887)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
```

~~Are there any possible mistakes/omissions I might have made while building/installing to look out for?~~ It appears (https://github.com/mandiant/Ghidrathon/issues/5) that autocomplete isn't a thing yet. Are there any potential problems if I run the Jython side-by-side for autocomplete and disable it before running scripts?

**Comment by mike-hunhoff** [comment]
@sad-dev thank you for reporting. You are correct that Ghidrathon does not yet support autocomplete, however, you have identified a bug that should be addressed.

You can run the Jython interpreter alongside Ghidrathon without needing to disable. Disabling Jython is simply a recommendation, not a requirement. Just note that when both are enabled Ghidrathon takes precendance over Jython when running scripts from the Ghidra script manager and in headless mode.
