### ISSUE TITLE
ClosedException is triggered when accessing AddressRangeMapDB in headless mode.

### ISSUE THREAD

**Issue by qkaiser** [mandiant/Ghidrathon#67]
### Environment Info

- OS: `Linux (Debian 11)`
- Python version: `3.10.12`
- Ghidra version: `10.3`
- Ghidrathon version: `2.2.1`
- openjdk version `17.0.7" 2023-04-18`

### Setup Info

I have a python script running as a `postScript` to Ghidra running in headless mode.

The script does something like this:

```python
FUNC_NAMES_LIST = ["printf"]

functions = list(currentProgram.getFunctionManager().getFunctions(True))

target_addresses = [
    func.getEntryPoint() for func in functions if func.getName() in FUNC_NAMES_LIST
]

references = itertools.chain.from_iterable(
    getReferencesTo(target_address) for target_address in target_addresses
)
```

I wanted to port it to Python3 using Ghidrathon but I'm getting `ClosedException` whenever I try to interact with the `AddressRangeMadDB` to get x-refs.

I'm getting the following stacktrace from Ghidra:

```
ERROR Unexpected Exception: File is closed (AddressRangeMapDB) ghidra.util.exception.ClosedException: File is closed
	at db.buffers.BufferMgr.getCachedBufferNode(BufferMgr.java:883)
	at db.buffers.BufferMgr.getBufferNode(BufferMgr.java:792)
	at db.buffers.BufferMgr.getBuffer(BufferMgr.java:956)
	at db.NodeMgr.getFixedKeyNode(NodeMgr.java:292)
	at db.Table.getFieldKeyNode(Table.java:166)
	at db.Table$ShortDurationFieldKeyIterator.initialize(Table.java:3852)
	at db.Table$ShortDurationFieldKeyIterator.<init>(Table.java:3826)
	at db.Table$FieldKeyIterator.<init>(Table.java:3370)
	at db.Table.fieldKeyIterator(Table.java:2005)
	at db.FieldIndexTable$PrimaryKeyIterator.<init>(FieldIndexTable.java:493)
	at db.FieldIndexTable.keyIterator(FieldIndexTable.java:410)
	at db.Table.indexIterator(Table.java:1569)
	at ghidra.program.database.util.AddressRangeMapDB.getAddressSet(AddressRangeMapDB.java:345)
	at ghidra.program.database.symbol.NamespaceManager.getAddressSet(NamespaceManager.java:292)
	at ghidra.program.database.symbol.NamespaceManager.getAddressSet(NamespaceManager.java:270)
	at ghidra.program.database.function.FunctionDB.getBody(FunctionDB.java:345)
	at ghidra.program.database.function.FunctionManagerDB.getFunctionContaining(FunctionManagerDB.java:534)
	at ghidra.program.database.ListingDB.getFunctionContaining(ListingDB.java:454)
	at ghidra.program.flatapi.FlatProgramAPI.getFunctionContaining(FlatProgramAPI.java:1042)
	at jep.Jep.invoke(Native Method)
	at jep.Jep.invoke(Jep.java:259)
	at ghidrathon.interpreter.GhidrathonInterpreter.runScript(GhidrathonInterpreter.java:426)
	at ghidrathon.GhidrathonScript.run(GhidrathonScript.java:41)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:397)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:252)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:230)
	at ghidra.app.util.headless.HeadlessAnalyzer.runScript(HeadlessAnalyzer.java:579)
	at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:912)
	at ghidra.app.util.headless.HeadlessAnalyzer.analyzeProgram(HeadlessAnalyzer.java:1060)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1544)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1662)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1709)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1727)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:448)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:127)
	at ghidra.GhidraLauncher.launch(GhidraLauncher.java:77)
	at ghidra.Ghidra.main(Ghidra.java:54)
ghidra.framework.model.DomainObjectException caused by: ghidra.util.exception.ClosedException: File is closed
Traceback (most recent call last):
--snip--
RuntimeError: ghidra.framework.model.DomainObjectException caused by: ghidra.util.exception.ClosedException: File is closed
```

**Comment by williballenthin** [comment]
possibly related to #65?

**Comment by mike-hunhoff** [comment]
Thank you for reporting @qkaiser - this is related to #65 . It appears to be a result of switching Ghidrathon to use Jep `SharedInterpreter`s in Ghidrathon `2.2.0`. Unfortunately I do not have a quick fix and I won't have time to fully triage and propose a fix until next week. In the mean time, please use [this previous Ghidrathon](https://github.com/mandiant/Ghidrathon/releases/tag/v2.1.0) release.

**Comment by mike-hunhoff** [comment]
@qkaiser this bug is fixed in our latest release: https://github.com/mandiant/Ghidrathon/releases/tag/v3.0.0.

**Comment by qkaiser** [comment]
great ! I'll give it a try next week :)

**Comment by qkaiser** [comment]
@mike-hunhoff works like a charm with the right modifications documented at https://github.com/mandiant/Ghidrathon#writing-ghidra-python-3-scripts

Thanks for the super fast fix and release ! :)
