### ISSUE TITLE
Unable to install on Intel MacOS - java.lang.UnsatisfiedLinkError of libjep.so

### ISSUE THREAD

**Issue by TheDauntless** [mandiant/Ghidrathon#78]
After building and installing the latest version, I get the following error:

```
Can't load library: /Users/jeroen/.ghidra/.ghidra_10.3.3_PUBLIC/Extensions/Ghidrathon-3.0.1/os/mac_x86_64/libjep.so
java.lang.UnsatisfiedLinkError: Can't load library: /Users/jeroen/.ghidra/.ghidra_10.3.3_PUBLIC/Extensions/Ghidrathon-3.0.1/os/mac_x86_64/libjep.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:1979)
	at jep.MainInterpreter.initialize(MainInterpreter.java:126)
	at jep.MainInterpreter.getMainInterpreter(MainInterpreter.java:101)
	at jep.Jep.<init>(Jep.java:133)
	at jep.SharedInterpreter.<init>(SharedInterpreter.java:60)
	at ghidrathon.interpreter.GhidrathonInterpreter.<init>(GhidrathonInterpreter.java:72)
	at ghidrathon.interpreter.GhidrathonInterpreter.get(GhidrathonInterpreter.java:232)
	at ghidrathon.GhidrathonConsoleInputThread.run(GhidrathonConsoleInputThread.java:66)

---------------------------------------------------
Build Date: 2023-Aug-29 1442 EDT
Ghidra Version: 10.3.3
Java Home: /Library/Java/JavaVirtualMachines/jdk-18.0.2.jdk/Contents/Home
JVM Version: Oracle Corporation 18.0.2
OS: Mac OS X 12.6 x86_64

```

The file is there though...

```
(.venv) ➜  mac_x86_64 ls -lah
total 1016
drwxr-x---  4 jeroen  staff   128B Sep  9 14:22 .
drwxr-x---  5 jeroen  staff   160B Sep  9 14:22 ..
-rw-r--r--  1 jeroen  staff   235B Sep  9 14:22 README.txt
-rwxr-xr-x  1 jeroen  staff   502K Sep  9 14:22 libjep.so
(.venv) ➜  mac_x86_64 file libjep.so 
libjep.so: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64Mach-O 64-bit bundle x86_64] [arm64:Mach-O 64-bit bundle arm64Mach-O 64-bit bundle arm64]
libjep.so (for architecture x86_64):	Mach-O 64-bit bundle x86_64
libjep.so (for architecture arm64):	Mach-O 64-bit bundle arm64
(.venv) ➜  mac_x86_64 pwd
/Users/jeroen/.ghidra/.ghidra_10.3.3_PUBLIC/Extensions/Ghidrathon-3.0.1/os/mac_x86_64
```

**Comment by TheDauntless** [comment]
I thought it might be related to https://github.com/ninia/jep/issues/432 so I built without a virtualenv. The new build throws the same exception unfortunately:

```
Can't load library: /Users/jeroen/.ghidra/.ghidra_10.3.3_PUBLIC/Extensions/Ghidrathon-3.0.1/os/mac_x86_64/libjep.so
java.lang.UnsatisfiedLinkError: Can't load library: /Users/jeroen/.ghidra/.ghidra_10.3.3_PUBLIC/Extensions/Ghidrathon-3.0.1/os/mac_x86_64/libjep.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:1979)
	at jep.MainInterpreter.initialize(MainInterpreter.java:126)
	at jep.MainInterpreter.getMainInterpreter(MainInterpreter.java:101)
	at jep.Jep.<init>(Jep.java:133)
	at jep.SharedInterpreter.<init>(SharedInterpreter.java:60)
	at ghidrathon.interpreter.GhidrathonInterpreter.<init>(GhidrathonInterpreter.java:72)
	at ghidrathon.interpreter.GhidrathonInterpreter.get(GhidrathonInterpreter.java:232)
	at ghidrathon.GhidrathonConsoleInputThread.run(GhidrathonConsoleInputThread.java:66)

---------------------------------------------------
Build Date: 2023-Aug-29 1442 EDT
Ghidra Version: 10.3.3
Java Home: /Library/Java/JavaVirtualMachines/jdk-18.0.2.jdk/Contents/Home
JVM Version: Oracle Corporation 18.0.2
OS: Mac OS X 12.6 x86_64
```

**Comment by mike-hunhoff** [comment]
Thank you for reporting @TheDauntless . This looks similar to an issue that is being discussed in #34 . Does the rpath patch suggested in https://github.com/mandiant/Ghidrathon/issues/34#issuecomment-1672590053 work for you? This may be something that we need to float upstream to the Jep developers.

**Comment by TheDauntless** [comment]
Thanks for the suggestion @mike-hunhoff . I had dismissed that post as I saw it was focussed on M1.

I can happily say that rpath was indeed missing and adding it using install_name_tool did the trick 🎉. Let me know if you would like more info for the Jep team.

**Comment by mike-hunhoff** [comment]
This should be addressed in https://github.com/mandiant/Ghidrathon/commit/32f3969e09a5d29197cabbc28d93dc9c572d7e45 - please reopen if you continue to have issues after this is released.
