### ISSUE TITLE
Why did Ghidrathon omit the println function?

### ISSUE THREAD

**Issue by hoanghai27** [mandiant/Ghidrathon#97]
I need to use the println function to log messages when running headless mode but I see that Ghidrathon is ignoring it. Why is that? Can you support it?

```
>>> println
Traceback (most recent call last):
  File "/home/user/.ghidra/.ghidra_11.0.1_PUBLIC/Extensions/Ghidrathon/data/python/jepeval.py", line 74, in jepeval
    more_input_needed = _jepeval(line)
                        ^^^^^^^^^^^^^^
  File "/home/user/.ghidra/.ghidra_11.0.1_PUBLIC/Extensions/Ghidrathon/data/python/jepeval.py", line 49, in _jepeval
    exec(compile(line, "<string>", "single"), globals(), globals())
  File "<string>", line 1, in <module>
NameError: name 'println' is not defined
```

https://github.com/mandiant/Ghidrathon/blob/91c0cab3ecdd01ec3327d577cc5e0b4e31a384ae/data/python/jepwrappers.py#L285C29-L285C34

**Comment by mike-hunhoff** [comment]
Thanks for reaching out @hoanghai27 . This specific line of code prevents overwriting Python's `print` function but you're correct that we should, if possible, add `ghidra.app.script.GhidraScript`'s `print`* methods (`println`, `printf`, `printerr`). I limited these methods initially because Ghidrathon has to wire the Python interpreter's `stdout`, `stderr` to the JVM's `stdout`, `stderr` and additional testing would be needed to ensure the additional methods function as expected after the wiring is configured.

In the mean time, are you able to use the `print` method for your needs here?

**Comment by hoanghai27** [comment]
Thanks for your feedback, I tried removing those two lines and found that both python's print function and Ghidra's println function work fine on both Ghidrathon console and scripts.

**Comment by Ephraim67** [comment]
Hi @mike-hunhoff, I'd be happy to help with this issue. Let me know if it has been assigned to someone else.

**Comment by mike-hunhoff** [comment]
Hi @Ephraim67 we're not actively working this project at the moment. While you're welcome to work on this issue, I can't make promises for when we'll get around to reviewing, approving, and merging your PR.
